### PR TITLE
Fixed recipe validation issues, added automated validation

### PR DESCRIPTION
**Pull request by jgstew**
I added automated validation using github actions. The same validations can be triggered through pre-commit directly. (except for plistlint which I need to build a pre-commit for)

I fixed many validation errors in a bunch of recipes.

WARNING: a few of the recipes had bad identifiers which I corrected, but this means these recipes will fail if the old identifiers are referenced in other things. There should be less than 10 total of these cases, and none of them were download recipes I think, so they shouldn't be referenced within any other recipes in the repo as far as I can tell.

Actually, the identifier changes are specifically in these:

- Google/GoogleSync-Win64.build/zzTest_GoogleSyncMSI-Win64.download.recipe
- Inkscape/Inkscape-Win64.build.recipe
- Jabref/Jabref-Win.build.recipe
- LibreOffice/LibreOffice-Win64.build.recipe

Only these 4 recipes have changes that may require updates to things that reference them down stream.

Once this PR is merged, I'm curious to experiment with this project to see how it converts recipes from plists to YAML: https://github.com/grahampugh/plist-yaml-plist 

I'm also curious if I can figure out a good way to automate the testing of autopkg recipes generically and only the ones that changed.

### CODE REVIEW

**Comment by jgstew** [comment]
@NickETH any feedback on this?

**Comment by NickETH** [comment]
Had a short look on it and it looks promising.
Will accept it, as soon as i fully understand everything.
Still on a learning curve with github... :-)
The real changes you mentioned look all like errors in the first place.

**Comment by jgstew** [comment]
You can see what is changed here: https://github.com/NickETH/recipes-win/pull/1/files

It does seem to all be real errors I found and corrected, it just might have some downstream effects in 4 cases.

**Comment by jgstew** [comment]
Also, something nice about the GitHub Actions... they won't prevent you from doing anything in this repo, and you won't have to change anything on your end when developing and commiting to here, BUT if you do something that doesn't pass validation, then the GitHub Action will alert you to that if you view the results.

You can optionally setup `pre-commit` locally and use the same pre-commit config I set up to automate the pre-commit validation in your local dev environment, but that is entirely optional and not required to get the valuable feedback from the GitHub action validation.

I like using pre-commit for this kind of thing because I can use it in both my local environment and GitHub Actions. I used to use many different github actions to run many different validators, but now I roll them all into pre-commit where I can.

**Pull request merged**
